spring:
  shell.interactive.enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false






logging:
  level:
    ROOT: error
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
#    org.hibernate.orm.jdbc.bind: trace